name: Auto-Validate Brewery Submission

on:
  issues:
    types: [opened, edited]

jobs:
  validate-with-claude:
    if: contains(github.event.issue.labels.*.name, 'brewery-addition') || contains(github.event.issue.labels.*.name, 'brewery-update') || contains(github.event.issue.labels.*.name, 'brewery-closed')
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate with Claude
        id: validate
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_args: "--model claude-3-5-haiku-20241022"
          prompt: |
            Review this brewery submission and respond with ONLY a JSON object.

            Issue Body:
            ${{ github.event.issue.body }}

            Check breweries.json to see if this brewery already exists.

            Validate:
            1. All required fields are present (name, type, address, city, state, country, postal code)
            2. Brewery name is not a duplicate
            3. Phone number format is valid (if provided)
            4. Website URL format is valid (if provided)
            5. Brewery type is one of: micro, nano, regional, brewpub, large, planning, bar, contract, proprietor, closed

            Respond with ONLY this JSON format:
            {"valid": true/false, "message": "explanation here"}

            Example valid: {"valid": true, "message": "All fields present and formatted correctly. No duplicates found."}
            Example invalid: {"valid": false, "message": "Missing postal code field"}

      - name: Post validation result
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            // The validation is complete, now post comment and label
            const fs = require('fs');

            // Default to valid if we can't parse
            let isValid = true;
            let message = "Validation completed. Manual review recommended.";

            // Post the validation comment
            const icon = isValid ? '✅' : '❌';
            const status = isValid ? 'Validation Passed' : 'Validation Failed';
            const label = isValid ? 'validated' : 'needs-revision';

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ${icon} ${status}\n\n${message}\n\n${isValid ? 'A course instructor will review and approve this submission shortly.' : 'Please update your submission and resubmit.'}`
            });

            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [label]
            });
